@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Ui as UiPackage {
Class "<<interface>>\nUi" as Ui
Class UiManager
}

package Logic as LogicPackage {
Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model as ModelPackage {
Class "<<interface>>\nModel" as Model
Class ModelManager
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .up.|> Logic
ModelManager .up.|> Model
StorageManager .up.|> Storage
UiManager .up.|> Ui

LogicManager --> Model
LogicManager --> Storage
UiManager --> Logic
@enduml
